# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake build & test

on:
  push:
    branches: [ "main" ]
    paths:
        - src/**
        - test/**
  pull_request:
    branches: [ "main" ]
    paths:
        - src/**
        - test/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [ ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        # combinazioni da includere
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        # combinazione da escludere
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Set output directory
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    - name: Upload artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.os}}-build
        path: ${{github.workspace}}/build
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        test: [edge_cases, empty, example, long, large, stress_cache, stress_cache2]
    steps:
    - uses: actions/checkout@v4
    - name: Download build files
      uses: actions/download-artifact@v4
      with:
        name: ubutu-build-files
        path: ${{github.workspace}}/build
    
    - name: "Display downloaded build files"
      run: ls -R
    - name: "Grant execution permission"
      working-directory: ${{github.workspace}}/build
      run: |
       chmod +x movehex
       chmod +x test/movehex_test
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release -R ^${{matrix.test}}$  --output-on-failure
